/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.meghdut.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;

import static com.meghdut.ui.UIUtils.setUpLookFeel;

/**
 * @author user
 */
public class LoginUI extends javax.swing.JFrame
{

    public static final int FAILED = 23;
    public static final int PASS = 33;

    public LoginUI()
    {
        setUpLookFeel();
        initComponents();
        setLocationRelativeTo(null);
        verify_panel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chat_id = new javax.swing.JTextField();
        verify_btn = new javax.swing.JButton();
        verify_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        code_4 = new javax.swing.JButton();
        code_3 = new javax.swing.JButton();
        code_2 = new javax.swing.JButton();
        code_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CaptureX Setup");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Step to Configure :- \n1. Open Telegram \n2. Create a new Group.(Optional)\n3. Add A Member to the Group.\n4. Search for CaptureX bot.\n5. A text will be sent by bot \"ChatID= XXXX\" \n6. Enter this code bellow and click on verify\n7. A Code will be again sent to the Group \n8. Select the correct code to verify.");
        jTextArea1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Chat ID ");

        chat_id.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        chat_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_idActionPerformed(evt);
            }
        });

        verify_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        verify_btn.setText("Verify");
        verify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_btnActionPerformed(evt);
            }
        });

        verify_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Verification Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Check the Group, And Click on the correct Code");

        code_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        code_4.setText("04");
        code_4.setMaximumSize(new java.awt.Dimension(50, 50));
        code_4.setMinimumSize(new java.awt.Dimension(50, 50));
        code_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_4ActionPerformed(evt);
            }
        });

        code_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        code_3.setText("03");
        code_3.setMaximumSize(new java.awt.Dimension(50, 50));
        code_3.setMinimumSize(new java.awt.Dimension(50, 50));
        code_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_3ActionPerformed(evt);
            }
        });

        code_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        code_2.setText("02");
        code_2.setMaximumSize(new java.awt.Dimension(50, 50));
        code_2.setMinimumSize(new java.awt.Dimension(50, 50));
        code_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_2ActionPerformed(evt);
            }
        });

        code_1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        code_1.setText("01");
        code_1.setMaximumSize(new java.awt.Dimension(50, 50));
        code_1.setMinimumSize(new java.awt.Dimension(50, 50));
        code_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verify_panelLayout = new javax.swing.GroupLayout(verify_panel);
        verify_panel.setLayout(verify_panelLayout);
        verify_panelLayout.setHorizontalGroup(
            verify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_panelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(verify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(verify_panelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(code_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(code_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(code_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(code_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        verify_panelLayout.setVerticalGroup(
            verify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verify_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code_4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextArea1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chat_id, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verify_btn))
                    .addComponent(verify_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chat_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(verify_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chat_idActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_chat_idActionPerformed

    }//GEN-LAST:event_chat_idActionPerformed

    private void verify_btnActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_verify_btnActionPerformed

    }//GEN-LAST:event_verify_btnActionPerformed

    private void code_4ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_code_4ActionPerformed

    }//GEN-LAST:event_code_4ActionPerformed

    private void code_3ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_code_3ActionPerformed

    }//GEN-LAST:event_code_3ActionPerformed

    private void code_2ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_code_2ActionPerformed

    }//GEN-LAST:event_code_2ActionPerformed

    private void code_1ActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_code_1ActionPerformed

    }//GEN-LAST:event_code_1ActionPerformed


    public void setUp(List<String> codes)
    {
        if (codes.size() != 4)
            throw new IllegalArgumentException("Exactly 4 Arguments are required!");
         verify_panel.setVisible(true);
        chat_id.setEnabled(false);
        code_1.setText(codes.get(0));
        code_2.setText(codes.get(1));
        code_3.setText(codes.get(2));
        code_4.setText(codes.get(3));
    }

    public void setUpCodeListener(StringHandler listener)
    {
        code_1.addActionListener(e -> listener.handle(code_1.getText()));
        code_2.addActionListener(e -> listener.handle(code_2.getText()));
        code_3.addActionListener(e -> listener.handle(code_3.getText()));
        code_4.addActionListener(e -> listener.handle(code_4.getText()));
    }

    public void setVerifyButtonListener(StringHandler listener)
    {
        verify_btn.addActionListener(e -> listener.handle(chat_id.getText().trim()));
    }

    public void info(String info)
    {
        JOptionPane.showMessageDialog(this, info);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code  ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        setUpLookFeel();
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new LoginUI().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chat_id;
    private javax.swing.JButton code_1;
    private javax.swing.JButton code_2;
    private javax.swing.JButton code_3;
    private javax.swing.JButton code_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton verify_btn;
    private javax.swing.JPanel verify_panel;
    // End of variables declaration//GEN-END:variables
}
