// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package proto;

public interface JoinPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.JoinPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>string deviceType = 3;</code>
   */
  java.lang.String getDeviceType();
  /**
   * <code>string deviceType = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string clipboard = 5;</code>
   */
  java.util.List<java.lang.String>
      getClipboardList();
  /**
   * <code>repeated string clipboard = 5;</code>
   */
  int getClipboardCount();
  /**
   * <code>repeated string clipboard = 5;</code>
   */
  java.lang.String getClipboard(int index);
  /**
   * <code>repeated string clipboard = 5;</code>
   */
  com.google.protobuf.ByteString
      getClipboardBytes(int index);
}
