// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string dest = 2;</code>
   * @return The dest.
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 2;</code>
   * @return The bytes for dest.
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   * @return The messageType.
   */
  proto.MessageType getMessageType();

  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   * @return Whether the messagePayload field is set.
   */
  boolean hasMessagePayload();
  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   * @return The messagePayload.
   */
  com.google.protobuf.Any getMessagePayload();
  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getMessagePayloadOrBuilder();
}
