// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string dest = 2;</code>
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   */
  int getMessageTypeValue();
  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   */
  proto.MessageType getMessageType();

  /**
   * <code>.tutorial.JoinPayload joinPayload = 4;</code>
   */
  boolean hasJoinPayload();
  /**
   * <code>.tutorial.JoinPayload joinPayload = 4;</code>
   */
  proto.JoinPayload getJoinPayload();
  /**
   * <code>.tutorial.JoinPayload joinPayload = 4;</code>
   */
  proto.JoinPayloadOrBuilder getJoinPayloadOrBuilder();

  /**
   * <code>string textPayload = 5;</code>
   */
  java.lang.String getTextPayload();
  /**
   * <code>string textPayload = 5;</code>
   */
  com.google.protobuf.ByteString
      getTextPayloadBytes();

  /**
   * <code>bytes bytesPayload = 6;</code>
   */
  com.google.protobuf.ByteString getBytesPayload();

  public proto.Message.PayloadCase getPayloadCase();
}
