// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_JoinPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_JoinPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_TextPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_TextPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ResponsePayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_ResponsePayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010tutorial\032\031google/protob" +
      "uf/any.proto\"}\n\007Message\022\n\n\002id\030\001 \001(\005\022\014\n\004d" +
      "est\030\002 \001(\t\022*\n\013messageType\030\003 \001(\0162\025.tutoria" +
      "l.MessageType\022,\n\016messagePayload\030\004 \001(\0132\024." +
      "google.protobuf.Any\"a\n\013JoinPayload\022\021\n\tti" +
      "mestamp\030\001 \001(\003\022\n\n\002id\030\002 \001(\005\022\022\n\ndeviceType\030" +
      "\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\021\n\tclipboard\030\005 \003(\t\"\033" +
      "\n\013TextPayload\022\014\n\004text\030\001 \001(\t\"!\n\017ResponseP" +
      "ayload\022\016\n\006status\030\001 \001(\t*\300\001\n\013MessageType\022\026" +
      "\n\022REQUEST_PASTE_TEXT\020\000\022\027\n\023REQUEST_PASTE_" +
      "IMAGE\020\001\022\023\n\017REQUEST_COPY_SS\020\002\022\027\n\023RESPONSE" +
      "_PASTE_TEXT\020\003\022\030\n\024RESPONSE_PASTE_IMAGE\020\004\022" +
      "\024\n\020RESPONSE_COPY_SS\020\005\022\017\n\013UPDATE_JOIN\020\006\022\021" +
      "\n\rUPDATE_CLIENT\020\007B\027\n\000B\021MessageOuterClass" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_tutorial_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Message_descriptor,
        new java.lang.String[] { "Id", "Dest", "MessageType", "MessagePayload", });
    internal_static_tutorial_JoinPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_JoinPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_JoinPayload_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "DeviceType", "Name", "Clipboard", });
    internal_static_tutorial_TextPayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_TextPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_TextPayload_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_tutorial_ResponsePayload_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tutorial_ResponsePayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_ResponsePayload_descriptor,
        new java.lang.String[] { "Status", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
