// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

/**
 * Protobuf type {@code tutorial.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    dest_ = "";
    messageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dest_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          case 34: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (messagePayload_ != null) {
              subBuilder = messagePayload_.toBuilder();
            }
            messagePayload_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messagePayload_);
              messagePayload_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageOuterClass.internal_static_tutorial_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageOuterClass.internal_static_tutorial_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Message.class, Message.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int DEST_FIELD_NUMBER = 2;
  private volatile java.lang.Object dest_;
  /**
   * <code>string dest = 2;</code>
   * @return The dest.
   */
  @java.lang.Override
  public java.lang.String getDest() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dest_ = s;
      return s;
    }
  }
  /**
   * <code>string dest = 2;</code>
   * @return The bytes for dest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestBytes() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 3;
  private int messageType_;
  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.tutorial.MessageType messageType = 3;</code>
   * @return The messageType.
   */
  @java.lang.Override public MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    MessageType result = MessageType.valueOf(messageType_);
    return result == null ? MessageType.UNRECOGNIZED : result;
  }

  public static final int MESSAGEPAYLOAD_FIELD_NUMBER = 4;
  private com.google.protobuf.Any messagePayload_;
  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   * @return Whether the messagePayload field is set.
   */
  @java.lang.Override
  public boolean hasMessagePayload() {
    return messagePayload_ != null;
  }
  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   * @return The messagePayload.
   */
  @java.lang.Override
  public com.google.protobuf.Any getMessagePayload() {
    return messagePayload_ == null ? com.google.protobuf.Any.getDefaultInstance() : messagePayload_;
  }
  /**
   * <code>.google.protobuf.Any messagePayload = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getMessagePayloadOrBuilder() {
    return getMessagePayload();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getDestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dest_);
    }
    if (messageType_ != MessageType.REQUEST_PASTE_TEXT.getNumber()) {
      output.writeEnum(3, messageType_);
    }
    if (messagePayload_ != null) {
      output.writeMessage(4, getMessagePayload());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getDestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dest_);
    }
    if (messageType_ != MessageType.REQUEST_PASTE_TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, messageType_);
    }
    if (messagePayload_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMessagePayload());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Message)) {
      return super.equals(obj);
    }
    Message other = (Message) obj;

    if (getId()
        != other.getId()) return false;
    if (!getDest()
        .equals(other.getDest())) return false;
    if (messageType_ != other.messageType_) return false;
    if (hasMessagePayload() != other.hasMessagePayload()) return false;
    if (hasMessagePayload()) {
      if (!getMessagePayload()
          .equals(other.getMessagePayload())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DEST_FIELD_NUMBER;
    hash = (53 * hash) + getDest().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    if (hasMessagePayload()) {
      hash = (37 * hash) + MESSAGEPAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getMessagePayload().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Message)
      MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageOuterClass.internal_static_tutorial_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageOuterClass.internal_static_tutorial_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Message.Builder.class);
    }

    // Construct using Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      dest_ = "";

      messageType_ = 0;

      if (messagePayloadBuilder_ == null) {
        messagePayload_ = null;
      } else {
        messagePayload_ = null;
        messagePayloadBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageOuterClass.internal_static_tutorial_Message_descriptor;
    }

    @java.lang.Override
    public Message getDefaultInstanceForType() {
      return Message.getDefaultInstance();
    }

    @java.lang.Override
    public Message build() {
      Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Message buildPartial() {
      Message result = new Message(this);
      result.id_ = id_;
      result.dest_ = dest_;
      result.messageType_ = messageType_;
      if (messagePayloadBuilder_ == null) {
        result.messagePayload_ = messagePayload_;
      } else {
        result.messagePayload_ = messagePayloadBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Message) {
        return mergeFrom((Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Message other) {
      if (other == Message.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getDest().isEmpty()) {
        dest_ = other.dest_;
        onChanged();
      }
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      if (other.hasMessagePayload()) {
        mergeMessagePayload(other.getMessagePayload());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dest_ = "";
    /**
     * <code>string dest = 2;</code>
     * @return The dest.
     */
    public java.lang.String getDest() {
      java.lang.Object ref = dest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dest = 2;</code>
     * @return The bytes for dest.
     */
    public com.google.protobuf.ByteString
        getDestBytes() {
      java.lang.Object ref = dest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dest = 2;</code>
     * @param value The dest to set.
     * @return This builder for chaining.
     */
    public Builder setDest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDest() {
      
      dest_ = getDefaultInstance().getDest();
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 2;</code>
     * @param value The bytes for dest to set.
     * @return This builder for chaining.
     */
    public Builder setDestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dest_ = value;
      onChanged();
      return this;
    }

    private int messageType_ = 0;
    /**
     * <code>.tutorial.MessageType messageType = 3;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.tutorial.MessageType messageType = 3;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.MessageType messageType = 3;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.tutorial.MessageType messageType = 3;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.MessageType messageType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any messagePayload_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> messagePayloadBuilder_;
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     * @return Whether the messagePayload field is set.
     */
    public boolean hasMessagePayload() {
      return messagePayloadBuilder_ != null || messagePayload_ != null;
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     * @return The messagePayload.
     */
    public com.google.protobuf.Any getMessagePayload() {
      if (messagePayloadBuilder_ == null) {
        return messagePayload_ == null ? com.google.protobuf.Any.getDefaultInstance() : messagePayload_;
      } else {
        return messagePayloadBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public Builder setMessagePayload(com.google.protobuf.Any value) {
      if (messagePayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messagePayload_ = value;
        onChanged();
      } else {
        messagePayloadBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public Builder setMessagePayload(
        com.google.protobuf.Any.Builder builderForValue) {
      if (messagePayloadBuilder_ == null) {
        messagePayload_ = builderForValue.build();
        onChanged();
      } else {
        messagePayloadBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public Builder mergeMessagePayload(com.google.protobuf.Any value) {
      if (messagePayloadBuilder_ == null) {
        if (messagePayload_ != null) {
          messagePayload_ =
            com.google.protobuf.Any.newBuilder(messagePayload_).mergeFrom(value).buildPartial();
        } else {
          messagePayload_ = value;
        }
        onChanged();
      } else {
        messagePayloadBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public Builder clearMessagePayload() {
      if (messagePayloadBuilder_ == null) {
        messagePayload_ = null;
        onChanged();
      } else {
        messagePayload_ = null;
        messagePayloadBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public com.google.protobuf.Any.Builder getMessagePayloadBuilder() {
      
      onChanged();
      return getMessagePayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getMessagePayloadOrBuilder() {
      if (messagePayloadBuilder_ != null) {
        return messagePayloadBuilder_.getMessageOrBuilder();
      } else {
        return messagePayload_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : messagePayload_;
      }
    }
    /**
     * <code>.google.protobuf.Any messagePayload = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getMessagePayloadFieldBuilder() {
      if (messagePayloadBuilder_ == null) {
        messagePayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getMessagePayload(),
                getParentForChildren(),
                isClean());
        messagePayload_ = null;
      }
      return messagePayloadBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.Message)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Message)
  private static final Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Message();
  }

  public static Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

