// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public interface ResponsePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ResponsePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
