// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public interface TextPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.TextPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
